# Generated by Django 4.1.1 on 2022-09-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendance_date_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date_completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
