# Generated by Django 4.1.1 on 2022-09-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_remove_attendance_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="present",
            field=models.BooleanField(
                choices=[(True, "Present"), (False, "Absent")], default=False, null=True
            ),
        ),
    ]
