# Generated by Django 4.1.1 on 2022-09-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_alter_attendance_present"),
    ]

    operations = [
        migrations.RemoveField(model_name="attendance", name="date_completed",),
        migrations.AddField(
            model_name="attendance",
            name="subject",
            field=models.CharField(default="null", max_length=140),
        ),
    ]
