# Generated by Django 4.1.1 on 2022-09-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_remove_attendance_date_completed_attendance_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance", name="summary", field=models.TextField(blank=True),
        ),
    ]
